# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AMaps
                                 A QGIS plugin
 Connector for the Azure Maps REST API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-05-16
        copyright            : (C) 2019 by Riccardo Klinger
        email                : riccardo.klinger@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AMaps class from file AMaps.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .amaps import AMaps
    return AMaps(iface)
